"""empty message

Revision ID: 3d0c4e15fe54
Revises: caa7fe0e30fd
Create Date: 2021-08-29 01:42:36.876826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0c4e15fe54'
down_revision = 'caa7fe0e30fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('inshop', sa.Integer(), nullable=True),
    sa.Column('whenarrived', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
